---
platform: linux
image_resource:
  type: registry-image
  source: {
    repository: node,
    tag: "18"
  }
inputs:
  - name: lcon-rpa-dashboard-ui-prod
outputs:
  - name: build
run:
  path: /bin/bash
  args:
    -  lcon-rpa-dashboard-ui-prod/ci/scripts/build_prod.sh