export enum SummaryType {
  TOTAL_OUTBOUND = 'totalOutbound',
  FIRST_OUTBOUND = 'firstOutbound',
  SECOND_OUTBOUND = 'secondOutbound',
  TOTAL_INBOUND = 'totalInbound',
  FIRST_INBOUND = 'firstInbound',
  SECOND_INBOUND = 'secondInbound',
  TOTAL_UNREACHABLE = 'totalUnreachable',
  INVALID = 'invalid',
  NO_RESPONSE = 'noResponse',
  NO_CHANGE = 'noChange',
  LCON_CHANGE = 'lconChange',
  ALCON_CHANGE = 'alconChange',
  DEMARC_CHANGE = 'demarcChange',
  TOTAL_SUCCESSFUL = 'totalSuccessful',
  TOTAL_FAILED = 'totalFailed',
}
